import { StyleSheet } from 'react-native';

import { colors } from '@theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.appBackground },

  iconSuccess: { color: colors.successText },
  iconPrimary: { color: colors.blue600 },
  iconWarning: { color: colors.amber500 },
  iconLabel: { color: colors.labelOnPrimary },

  // Header
  header: {
    backgroundColor: colors.blue600,
    paddingTop: 60,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    gap: 6,
  },
  posisi: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.whiteAlpha70,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  judul: { fontSize: 22, fontWeight: '800', color: colors.labelOnPrimary, lineHeight: 30 },
  deskripsi: { fontSize: 13, color: colors.whiteAlpha75, lineHeight: 20 },
  headerMeta: { flexDirection: 'row', gap: 16, marginTop: 8 },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  metaLabel: { fontSize: 12, color: colors.whiteAlpha80 },

  // Banner
  bannerSudahVote: {
    margin: 20,
    marginBottom: 0,
    backgroundColor: colors.successBg,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.successBorder,
  },
  bannerTitle: { fontSize: 15, fontWeight: '700', color: colors.successText },
  bannerSub: { fontSize: 12, color: colors.successMuted, marginTop: 2 },
  bannerDitutup: { borderColor: colors.blue300, backgroundColor: colors.infoBg },

  // Tie banner
  bannerTie: {
    margin: 20,
    marginBottom: 0,
    backgroundColor: colors.warningBg,
    borderRadius: 16,
    padding: 16,
    gap: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.warningBorder,
  },
  bannerTieTitle: { fontSize: 16, fontWeight: '800', color: colors.warningText },
  bannerTieSub: { fontSize: 13, color: colors.warningMuted, lineHeight: 19 },

  // Section
  section: { padding: 20, paddingBottom: 0 },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.slate800,
  },
  sectionSub: { fontSize: 12, color: colors.slate400, marginBottom: 16 },

  // Kandidat card
  kandidatCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 18,
    flexDirection: 'row',
    gap: 14,
    marginBottom: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  kandidatCardSelected: {
    borderWidth: 2,
    borderColor: colors.blue600,
    backgroundColor: colors.infoBg,
    shadowColor: colors.blue600,
    shadowOpacity: 0.11,
    elevation: 4,
  },
  nomorUrut: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.slate100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nomorUrutSelected: { backgroundColor: colors.blue600 },
  nomorUrutText: { fontSize: 20, fontWeight: '800', color: colors.slate500 },

  kandidatBody: { flex: 1, gap: 6 },
  kandidatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  kandidatNama: { fontSize: 17, fontWeight: '700', color: colors.slate800, flex: 1 },
  visiRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 },
  misiRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6 },
  visiMisiText: { flex: 1, fontSize: 13, color: colors.slate500, lineHeight: 19 },

  // Progress
  hasilBox: { marginTop: 8, gap: 5 },
  progressTrack: {
    height: 8,
    backgroundColor: colors.slate200,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBar: { height: '100%', backgroundColor: colors.blue600, borderRadius: 4 },
  hasilText: { fontSize: 12, color: colors.blue600, fontWeight: '600' },

  // Hasil button
  btnHasil: {
    backgroundColor: colors.infoBg,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.infoBorder,
  },
  btnHasilText: { color: colors.blue600, fontWeight: '700', fontSize: 15 },

  // Sticky bottom
  stickyBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.surface,
    padding: 20,
    paddingBottom: 32,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.07,
    elevation: 8,
  },
  btnVote: {
    backgroundColor: colors.blue600,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    shadowColor: colors.blue600,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    elevation: 4,
  },
  btnVoteDisabled: { backgroundColor: colors.slate400, shadowOpacity: 0 },
  btnVoteRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  btnVoteText: { color: colors.labelOnPrimary, fontWeight: '800', fontSize: 16 },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.blackAlpha55,
    justifyContent: 'center',
    padding: 28,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    padding: 32,
    alignItems: 'center',
    gap: 10,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.11,
    elevation: 8,
  },
  modalTitle: { fontSize: 22, fontWeight: '800', color: colors.slate800 },
  modalSub: { fontSize: 14, color: colors.slate500 },
  modalCandidateBox: {
    backgroundColor: colors.infoBg,
    borderRadius: 16,
    padding: 20,
    width: '100%',
    alignItems: 'center',
    gap: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.infoBorder,
  },
  modalCandidateName: { fontSize: 20, fontWeight: '800', color: colors.blue600 },
  modalCandidateUrut: { fontSize: 13, color: colors.slate500 },
  modalWarningRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    paddingHorizontal: 4,
  },
  modalWarning: {
    flex: 1,
    fontSize: 12,
    color: colors.amber500,
    lineHeight: 18,
  },
  modalButtons: { flexDirection: 'row', gap: 12, width: '100%', marginTop: 8 },
  btnBatal: {
    flex: 1,
    backgroundColor: colors.slate100,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
  },
  btnBatalText: { fontWeight: '700', color: colors.slate500, fontSize: 15 },
  btnKonfirmasi: {
    flex: 1,
    backgroundColor: colors.blue600,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    shadowColor: colors.blue600,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    elevation: 3,
  },
  btnKonfirmasiText: { fontWeight: '700', color: colors.labelOnPrimary, fontSize: 15 },
});
