import { StyleSheet } from 'react-native';

import { colors } from '@theme/colors';

export const COLORS = [
  colors.blue600,
  colors.successMuted,
  colors.amber600,
  colors.violet600,
  colors.errorStrong,
];

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.appBackground },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 14,
    padding: 32,
    backgroundColor: colors.appBackground,
  },
  errorTitle: { fontSize: 18, fontWeight: '700', color: colors.slate800 },
  errorMsg: { fontSize: 14, color: colors.slate600, textAlign: 'center' },
  btnBack: {
    backgroundColor: colors.blue600,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 8,
  },
  btnBackRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  btnBackText: { color: colors.labelOnPrimary, fontWeight: '600' },

  header: {
    backgroundColor: colors.blue600,
    paddingTop: 60,
    paddingBottom: 28,
    paddingHorizontal: 24,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    gap: 6,
  },
  headerLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.whiteAlpha60,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  headerTitle: { fontSize: 20, fontWeight: '800', color: colors.labelOnPrimary },
  statusBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    marginTop: 4,
  },
  badgeSelesai: { backgroundColor: colors.whiteAlpha20 },
  badgeAktif: { backgroundColor: colors.whiteAlpha25 },
  statusBadgeRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  statusText: { fontSize: 12, fontWeight: '700', color: colors.labelOnPrimary },

  totalBox: {
    alignItems: 'center',
    paddingVertical: 24,
    backgroundColor: colors.surface,
    margin: 20,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    elevation: 2,
  },
  totalAngka: { fontSize: 48, fontWeight: '900', color: colors.blue600 },
  totalLabel: {
    fontSize: 14,
    color: colors.slate400,
    fontWeight: '600',
    marginTop: 2,
  },

  // Tie
  badgeTie: { backgroundColor: colors.amberAlpha15 },
  bannerTie: {
    margin: 20,
    marginBottom: 8,
    backgroundColor: colors.warningBg,
    borderRadius: 16,
    padding: 16,
    gap: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.warningBorder,
  },
  bannerTieTitle: { fontSize: 15, fontWeight: '800', color: colors.warningText },
  bannerTieSub: { fontSize: 13, color: colors.warningMuted, lineHeight: 19 },
  bannerAktif: {
    margin: 20,
    marginBottom: 8,
    backgroundColor: colors.infoBg,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.infoBorder,
  },
  bannerAktifTitle: { fontSize: 14, fontWeight: '800', color: colors.infoText },
  bannerAktifSub: { fontSize: 12, color: colors.infoText, lineHeight: 18, marginTop: 2 },
  tieTag: { fontSize: 11, fontWeight: '700', color: colors.amber600 },
  barRowLeading: {
    borderWidth: 2,
    borderColor: colors.blue300,
    backgroundColor: colors.infoBg,
  },
  leadingTag: { fontSize: 11, fontWeight: '700', color: colors.blue600 },
  catatanBox: {
    margin: 20,
    marginTop: 8,
    backgroundColor: colors.warningBg,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.warningBorder,
    alignItems: 'flex-start',
  },
  catatanText: { flex: 1, fontSize: 13, color: colors.warningText, lineHeight: 19 },

  // Pemenang
  pemenangCard: {
    margin: 20,
    marginTop: 0,
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 28,
    alignItems: 'center',
    gap: 6,
    borderWidth: 2,
    borderColor: colors.amber400,
    shadowColor: colors.amber500,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.11,
    elevation: 4,
  },
  pemenangMahkota: { fontSize: 44, marginBottom: 4 },
  pemenangLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.amber500,
    letterSpacing: 2,
  },
  pemenangNama: {
    fontSize: 26,
    fontWeight: '900',
    color: colors.slate800,
    textAlign: 'center',
  },
  pemenangPosisi: { fontSize: 13, color: colors.slate600 },
  pemenangStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 20,
  },
  statDivider: { width: 1, height: 36, backgroundColor: colors.slate200 },
  statBox: { alignItems: 'center', gap: 2 },
  statNilai: { fontSize: 22, fontWeight: '800', color: colors.blue600 },
  statLabel: { fontSize: 11, color: colors.slate400, fontWeight: '600' },

  // Chart
  section: { paddingHorizontal: 20, paddingBottom: 0 },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.slate800,
  },

  barRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    padding: 16,
    marginBottom: 12,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    elevation: 1,
  },
  barRowWinner: {
    borderWidth: 2,
    borderColor: colors.amber400,
    backgroundColor: colors.amber50,
  },
  barLeft: { flex: 1, gap: 8 },
  barHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  barNama: { fontSize: 15, fontWeight: '700', color: colors.slate800, flex: 1 },
  winnerTag: { fontSize: 11, fontWeight: '700', color: colors.amber600 },
  barTrack: {
    height: 10,
    backgroundColor: colors.slate100,
    borderRadius: 5,
    overflow: 'hidden',
  },
  barFill: { height: '100%', borderRadius: 5 },
  barRight: { alignItems: 'flex-end', gap: 2, minWidth: 60 },
  barPersen: { fontSize: 18, fontWeight: '800' },
  barSuara: { fontSize: 11, color: colors.slate400 },

  // Anonimitas
  anonBox: {
    margin: 20,
    backgroundColor: colors.slate50,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    alignItems: 'flex-start',
  },
  anonText: { flex: 1, fontSize: 12, color: colors.slate600, lineHeight: 18 },

  btnBack2: {
    marginHorizontal: 20,
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  btnBack2Row: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  btnBack2Text: { color: colors.slate600, fontWeight: '600', fontSize: 14 },
});
